site_name: D&D Campaign Wiki
site_url: https://dnd.jevex.net

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.code.copy
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - footnotes
    - navigation.path
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    # - navigation.sections
    - navigation.tabs
    - navigation.top
    - toc.follow

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - material.extensions.preview:
      targets:
        include:
          - command/argument-types.md
  - md_in_html
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - tables
  - toc:
      permalink: true

plugins:
  - mkdnd
  - search
  - typeset

  # INSIDERS=1 mkdocs build
  - group:
      enabled: !ENV INSIDERS
      plugins:
        - optimize:
            enabled: !ENV [CI, false]
        - privacy
        - tags:
            tags_hierarchy: true

nav:
  - Home:
      - index.md
  - Danteria:
      - danteria/index.md
      - Geography:
          - danteria/geography/index.md
          - Zellatin: danteria/geography/zellatin.md
